---
- name: Add Jetstack repository
  command: helm repo add jetstack https://charts.jetstack.io

- name: Update Helm repositories
  command: helm repo update

- name: Template cert-manager values
  template:
    src: cert-manager-values.yaml.j2
    dest: /tmp/cert-manager-values.yaml

- name: Deploy cert-manager
  command: >
    helm upgrade --install cert-manager jetstack/cert-manager
    --version {{ cert_manager_version }}
    --namespace cert-manager --create-namespace
    -f /tmp/cert-manager-values.yaml