---
- name: Add Jetstack Helm repository
  command: helm repo add jetstack https://charts.jetstack.io
  become: yes

- name: Update Helm repositories
  command: helm repo update
  become: yes

- name: Template cert-manager values
  template:
    src: cert-manager-values.yaml.j2
    dest: /tmp/cert-manager-values.yaml

- name: Deploy cert-manager
  command: >
    helm upgrade --install cert-manager jetstack/cert-manager
    --version {{ cert_manager_version }}
    --namespace cert-manager --create-namespace
    -f /tmp/cert-manager-values.yaml
    --set installCRDs=true
  become: yes

- name: Wait for cert-manager to be ready
  command: kubectl wait --for=condition=available --timeout=300s deployment/cert-manager -n cert-manager
  become: yes

- name: Template ClusterIssuer
  template:
    src: cluster-issuer.yaml.j2
    dest: /tmp/cluster-issuer.yaml

- name: Apply ClusterIssuer
  command: kubectl apply -f /tmp/cluster-issuer.yaml
  become: yes