---
- name: Add ArgoCD repository
  command: helm repo add argo https://argoproj.github.io/argo-helm

- name: Update Helm repositories
  command: helm repo update

- name: Template ArgoCD values
  template:
    src: argocd-values.yaml.j2
    dest: /tmp/argocd-values.yaml

- name: Deploy ArgoCD
  command: >
    helm upgrade --install argocd argo/argo-cd
    --version {{ argocd_version }}
    --namespace argocd --create-namespace
    -f /tmp/argocd-values.yaml
    --kubeconfig /etc/rancher/k3s/k3s.yaml
  become: yes
- name: Set KUBECONFIG environment variable
  ansible.builtin.set_fact:
    ansible_environment: "{{ ansible_environment | combine({'KUBECONFIG': '/etc/rancher/k3s/k3s.yaml'}) }}"  