- name: Install K3s
  shell: |
    curl -sfL https://get.k3s.io | sh -s - \
    --write-kubeconfig-mode 644 \
    --tls-san {{ ansible_host }}
  args:
    creates: /usr/local/bin/k3s
  register: k3s_install_result

- name: Display K3s installation result
  debug:
    var: k3s_install_result

- name: Check K3s binary
  stat:
    path: /usr/local/bin/k3s
  register: k3s_binary

- name: Display K3s binary status
  debug:
    var: k3s_binary