---
- name: Add Ingress Nginx repository
  command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

- name: Update Helm repositories
  command: helm repo update

- name: Template Ingress Nginx values
  template:
    src: ingress-values.yaml.j2
    dest: /tmp/ingress-values.yaml

- name: Deploy Ingress Nginx
  command: >
    helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
    --version {{ ingress_nginx_version }}
    --namespace ingress-nginx --create-namespace
    -f /tmp/ingress-values.yaml