---
- hosts: k3s_cluster
  become: yes
  vars:
    ansible_play_name: "install"
  roles:
    - k3s
- hosts: k3s_cluster
  roles:
    - { role: helm, when: install_helm | bool }
    - { role: ingress_nginx, when: install_ingress_nginx | bool }
    - { role: argocd, when: install_argocd | bool }
    - { role: dashboard, when: install_dashboard | bool }
    - { role: cert_manager, when: install_cert_manager | bool }
